spring:
  datasource:
#    host：cdb-ctmslwcn.gz.tencentcdb.com
#    port：10020
#    username：se
#    password：sufese777
    username: se
    password: sufese777
    url: jdbc:mysql://cdb-ctmslwcn.gz.tencentcdb.com:10020/laptop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.laptop.demo.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
server:
  port: 80